name: Run tests and deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
    steps:
      - name: Clonar código
        uses: actions/checkout@v4
      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Instalar dependencias
        run: npm install
      - name: Ejecutar tests
        run: npm test
        env:
          MONGO_URL: mongodb://localhost:27017/test
      - name: Desplegar en Render
        if: success()
        run: curl -f ${{ secrets.RENDER_DEPLY_HOOK }}